version: '2'
services:
  trackr-app:
    image: trackr
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://trackr-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=trackr
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  trackr-mongodb:
    extends:
      file: mongodb.yml
      service: trackr-mongodb
