export enum RegisterTypeEnum {
  ORGANISATION = "ORGANISATION",
  EMPLOYEE = "EMPLOYEE",
}

export enum RegisterStepEnum {
  REGISTER_TYPE = "REGISTER_TYPE",
  REGISTER_ORG_DETAILS = "REGISTER_ORG_DETAILS",
  REGISTER_USER_DETAILS = "REGISTER_USER_DETAILS",
}
